development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['MYSQL2_DATABASE_DEVELOPMENT'] %>
  pool: 5
  username: <%= ENV['MYSQL2_USERNAME_DEVELOPMENT'] %>
  password: <%= ENV['MYSQL2_PASSWORD_DEVELOPMENT'] %>
  host: <%= ENV['MYSQL2_HOST_DEVELOPMENT'] %>

test:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['MYSQL2_DATABASE_TEST'] %>
  pool: 5
  username: <%= ENV['MYSQL2_USERNAME_TEST'] %>
  password: <%= ENV['MYSQL2_PASSWORD_TEST'] %>
  host: <%= ENV['MYSQL2_HOST_TEST'] %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gogreen
  pool: 5
  username: root
  password:
