development:
  adapter: mysql2
  encoding: utf8
  database: gogreen_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: gogreen_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gogreen
  pool: 5
  username: root
  password:
